int print_char(char c);
void print_z(void);
void print_alphabet(void);
void print_tebahpla(void);
void print_base16(void);
void positive_or_not(int n);
void print_number(int n);
void print_combination_1(void);
void print_combination_2(void);
void print_combination_3(void);
void print_combination_4(void);
