int print_char(char);
char *concat_strings(char *, char *);
int str_len(char *);
int str_cmp(char *, char *);
int *print_prompt();
void print_env(char **);
char *find_path(char *, char **);
int ch_dir(char *, char **);
char *get_env_var(char *, char **);
void free_grid(char **, int);
int grid_size(char **);
char **prompt(void);
char usage(int, int, char *);
char *get_env_value(char *, char **);
void replace_expr(char *, int, char **);
char *int_to_str(int, int, char *);
int find_len(int);
char *min(char *);
char *int_to_string(int);
void print_string(char *);
