void positive_or_not(int n);
void print_number(int n);
int absolute(int);
char uppercase(char);
char lowercase(char);
int first_digit(int);
void swap_int(int *a, int *b);
int str_len(char *s);
void print_string(char *str);
void reverse_string(char *s);
int string_to_integer(char *s);
void print_array(int *a, int n);
char *concat_strings(char *dest, const char *src);
char *nconcat_strings(char *dest, const char *src, int n);
char *string_copy(char *dest, const char *src);
char *string_ncopy(char *dest, const char *src, int n);
int strings_compare(char *s1, const char *s2);
void reverse_array(int *a, int n);
char *uppercase_string(char *);
char *cap_string(char *);
int power(int x, int y);
int square_root(int n);
int is_prime_number(int n);
int print_char(char c);
